### PR TITLE
pin tools using go.mod

### PR DESCRIPTION
**Pull request by dhellmann**
Take the same approach used in baremetal-operator to specify the version
of controller-gen and kustomize to use with this repository.

See https://github.com/metal3-io/baremetal-operator/pull/691 and
https://github.com/metal3-io/baremetal-operator/pull/688

### CODE REVIEW

**Comment by dhellmann** [comment]
This also updates the version of controller-gen, which changes the generated output for the CRD. It should be backwards-compatible.

**Comment by dhellmann** [comment]
> This also updates the version of controller-gen, which changes the generated output for the CRD. It should be backwards-compatible.

There's something wrong with the unit test job that prevents that aspect of the change from working, so I've forced the CRD version to `v1beta1` for now.

**Review by digambar15 — APPROVED** [review]
looks good.

**Pull request merged**
