### PR TITLE
Modified Dockerfile and minor log change.

### PR DESCRIPTION
**Pull request by Ashughorla**
Modified Dockerfile according to new file structure.
Changed 1 log info in disk.go file.

Kindly review.
@dhellmann @maelk @digambar15

### CODE REVIEW

**Comment by Ashughorla** [comment]
@maelk 
Kindly provide /lgtm if PR is ok to merge.

**Comment by Ashughorla** [comment]
Hello @maelk, please merge this PR.
All changes are tested and approved.

**Review by maelk — APPROVED** [review]

**Comment by maelk** [comment]
/lgtm
Sorry for the delay

**Pull request merged**
