### PR TITLE
Bump the Golang version to 1.16

### PR DESCRIPTION
**Pull request by fmuyassarov**
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)
/hold until metal3-io/project-infra#172 gets merged
/cc @maelk

### CODE REVIEW

**Comment by maelk** [comment]
/approve
but this should get the green light from some of the main developers of this project

**Comment by fmuyassarov** [comment]
/hold cancel
since metal3-io/project-infra#172 is merged now.

**Comment by sumitjadhav1** [comment]
/cc @dhellmann 
/cc @digambar15
Please take a look, this is waiting for lgtm label

**Comment by digambar15** [comment]
Looks Good.

**Pull request merged**
