### PR TITLE
Firmware Implmentation

### PR DESCRIPTION
**Pull request by ravipwaghmare**
Added Firmware code with version check.
Added test cases for firmware code

This PR is related to the below proposal and issue:
https://github.com/metal3-io/metal3-docs/pull/147
https://github.com/metal3-io/hardware-classification-controller/issues/56

@dhellmann @maelk  @digambar15 @russellb @zaneb 
kindly review.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@ravipwaghmare Would you mind to add a reference in the PR description to the proposal?

**Comment by Ashughorla** [comment]
@fmuyassarov Proposal link and Issue link updated in description.

**Review by digambar15 — APPROVED** [review]
Looks good

**Comment by digambar15** [comment]
Code looks good. Thanks Ravi!

**Pull request merged**
