### PR TITLE
Upgrade to CRD API to v1

### LINKED ISSUE #62: Upgrade to CRD API to apiextensions.k8s.io/v1
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition will no not be served anymore starting from K8s v1.22. We should upgrade all our CRDs to v1.

Reference document: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

### PR DESCRIPTION
**Pull request by fmuyassarov**
Fixes: https://github.com/metal3-io/hardware-classification-controller/issues/62

### CODE REVIEW

**Comment by ravipwaghmare** [comment]
Hi @fmuyassarov please rebase your branch with master.

**Comment by fmuyassarov** [comment]
I'm a bit confused if the issue is related to the version of the Kubebuilder I have locally installed. I tried to upgrade it but still seeing this issue in unit test.
```
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  occurred
```

**Comment by Ashughorla** [comment]
@fmuyassarov please rebase.

**Comment by ravipwaghmare** [comment]
Hi, @fmuyassarov Please rebase your branch as two PR got merged last week.

**Comment by fmuyassarov** [comment]
I'm going for vacation and don't have time to debug the failing unit tests. @Ashughorla agreed to work on this on a new PR. As such, closing mine.
/close

**Pull request closed without merging**
