### PR TITLE
Changed namespace to hardware-classification

### PR DESCRIPTION
**Pull request by sharajat**
In this PR, changed namespace from system to hardware-classification and changed controller-manager name to  hardware-classification-controller-manager.
@digambar15 @maelk kindly review.

### CODE REVIEW

**Comment by maelk** [comment]
Can you provide some explanation on this change ? The kustomization was taking care of doing exactly what you are now doing manually. Why this change then ?

**Comment by digambar15** [comment]
We finalized only namespace as hardware-classification. Kustomization is taking care of it only when we try to deploy via kustomize. I think we have to correct the namespace in existing codebase. If try to run HCC locally or in containers, it only runs the HCC under hcc-system namespace.

**Comment by maelk** [comment]
The config folder is to be used with Kustomize. The controller itself can watch a specific namespace if you give it as a parameter (this parameterization might be missing for this controller) and I think that would be a better approach than hardcoding it

**Comment by sharajat** [comment]
@maelk @digambar15 removed hardcoding of namespace, added watchNamespace and seperated namespace.yaml as kustomize was applying namePrefix to kind namespace also. Kindly review.

**Review by maelk — COMMENTED** [review]
/lgtm

**Pull request merged**
