### PR TITLE
Hardware classification

### PR DESCRIPTION
**Pull request by Ashughorla**
Hardware Classification boiler plate code.
With new name HardwareClassification suggested in approved PR-60

### CODE REVIEW

**Comment by Ashughorla** [comment]
/assign @digambar15
Please review.

**Comment by digambar15** [comment]
@dhellmann  I think we should the repo name to hardware-classification (Instead of hardware-classification-controller) as per latest design proposal.

**Comment by digambar15** [comment]
@Ashughorla  Please resolve conflicts

**Comment by dhellmann** [comment]
> @dhellmann I think we should the repo name to hardware-classification (Instead of hardware-classification-controller) as per latest design proposal.

I only objected to including "controller" in the API name because it's not accurate. The CRD is not the controller.

This repository will contain the code for the new controller, so the existing name seems OK to me. It's consistent with the use of "operator" in the "baremetal-operator" repository.

What do you think?

**Pull request closed without merging**
